import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,Boxes,LayoutDashboard,PlayCircle,ShieldCheck} from "lucide-react";
import "./style.css";

const strategies=[["Standard","Simple estate-wide or targeted patching"],["Rolling / Batch","Controlled batches with concurrency limits"],["Canary / Ring","Progressive promotion through deployment rings"],["Tier Based","Application, middleware and database sequencing"],["Cluster / DB","Node-aware rolling patch and failover gates"],["Hybrid","Custom dependency-driven orchestration"]];

function Wizard({close}:{close:()=>void}){
 const [step,setStep]=useState(1); const [strategy,setStrategy]=useState("Tier Based");
 return <div className="modal"><div className="wizard"><div className="wizardHead"><div><small>CREATE CAMPAIGN</small><h2>New patch campaign</h2></div><button className="secondary" onClick={close}>Close</button></div>
 <div className="steps">{["Campaign Type","Basic Details","Target Selection","Patch Content","Execution","Review"].map((x,i)=><span className={step===i+1?"active":""} key={x}>{i+1}. {x}</span>)}</div>
 {step===1&&<div><h3>Choose orchestration strategy</h3><div className="strategies">{strategies.map(([n,d])=><article onClick={()=>setStrategy(n)} className={strategy===n?"selected":""} key={n}><div className="icon"><Boxes/></div><h3>{n}</h3><p>{d}</p></article>)}</div></div>}
 {step===2&&<div className="form"><label>Campaign Name<input defaultValue="October Critical Patching - ERP"/></label><label>Description<textarea defaultValue="Monthly security patching for ERP production"/></label><div className="row"><label>Business Unit<select><option>ERP</option><option>Finance</option></select></label><label>Environment<select><option>Production</option><option>UAT</option><option>Development</option></select></label></div><label>Change Ticket<input placeholder="CHG0123456"/></label></div>}
 {step===3&&<div><h3>Select Application / Topology</h3><div className="row"><label className="grow">Application<select><option>ERP (Production)</option><option>Internet Banking (Production)</option></select></label></div><div className="topology"><b>Load Balancer (2)</b><div>↓</div><section><strong>APP Tier<br/>42 servers</strong><strong>Middleware<br/>28 servers</strong><strong>Database<br/>8 servers</strong></section></div><div className="scope"><label><input type="radio" defaultChecked name="scope"/> All tiers</label><label><input type="radio" name="scope"/> Specific tiers</label><label><input type="radio" name="scope"/> Server groups</label></div></div>}
 {step===4&&<div><h3>Patch Content</h3><table><thead><tr><th></th><th>Patch</th><th>OS</th><th>Severity</th><th>Reboot</th></tr></thead><tbody>{[["KB5031354","Windows","Critical","Yes"],["KB5030211","Windows","Important","No"],["RHSA-2024:4567","Linux","Critical","Yes"],["RHSA-2024:3421","Linux","Important","No"]].map(r=><tr><td><input type="checkbox" defaultChecked/></td>{r.map(x=><td>{x}</td>)}</tr>)}</tbody></table></div>}
 {step===5&&<div className="form"><h3>{strategy} execution options</h3><div className="row"><label>Batch / Canary Size<input defaultValue="5"/></label><label>Success Threshold %<input defaultValue="95"/></label></div><div className="row"><label>Failure Action<select><option>Pause campaign</option><option>Continue</option></select></label><label>Reboot<select><option>Reboot if required</option><option>Suppress</option></select></label></div><label><input type="checkbox" defaultChecked/> Require application health check before promotion</label></div>}
 {step===6&&<div><h3>Review campaign</h3><div className="review"><p><b>Strategy</b><span>{strategy}</span></p><p><b>Application</b><span>ERP (Production)</span></p><p><b>Targets</b><span>78 servers</span></p><p><b>Promotion threshold</b><span>95%</span></p><p><b>Reboot</b><span>If required</span></p></div><button>Submit for Approval</button></div>}
 <div className="wizardActions"><button className="secondary" disabled={step===1} onClick={()=>setStep(step-1)}>Back</button>{step<6&&<button onClick={()=>setStep(step+1)}>Next →</button>}</div></div></div>
}

function App(){const [wizard,setWizard]=useState(false);return <div className="shell"><aside><div className="brand"><ShieldCheck/> UPO</div><nav><b><LayoutDashboard/> Overview</b><span><PlayCircle/> Campaigns</span><span><Boxes/> Applications</span><span><Boxes/> Topology</span><span><Activity/> Providers</span></nav></aside><main><header><div><small>UNIVERSAL PATCH ORCHESTRATOR</small><h1>Patch operations</h1><p>Plan and control patching across providers from one control plane.</p></div><button onClick={()=>setWizard(true)}>+ New campaign</button></header><section className="stats"><article><small>ACTIVE CAMPAIGNS</small><strong>3</strong><em>1 executing now</em></article><article><small>ENDPOINTS IN SCOPE</small><strong>1,240</strong><em>Across all providers</em></article><article><small>COMPLIANCE</small><strong>94.7%</strong><em>Last completed campaigns</em></article><article><small>PROVIDER HEALTH</small><strong>Healthy</strong><em>BigFix connected</em></article></section><h2>Choose an orchestration strategy</h2><section className="strategies">{strategies.map(([n,d])=><article key={n}><div className="icon"><Boxes/></div><h3>{n}</h3><p>{d}</p><span>Configure →</span></article>)}</section><section className="panel"><small>LIVE EXECUTION</small><h2>October Critical Security Patching</h2><p>Canary / Ring deployment · 1,240 endpoints</p><div className="rings"><b>✓ Canary</b><i></i><b>✓ Ring 1</b><i></i><b className="running">● Ring 2 · 71%</b><i></i><b className="blocked">Ring 3 · Blocked</b></div></section></main>{wizard&&<Wizard close={()=>setWizard(false)}/>}</div>}
createRoot(document.getElementById("root")!).render(<App/>);